services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tuum'
      - 'POSTGRES_PASSWORD=parool'
      - 'POSTGRES_USER=kasutaja'
    ports:
      - '5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=parool'
      - 'RABBITMQ_DEFAULT_USER=kasutaja'
    ports:
      - '5672'
